name: Build, Release, and Deploy

on:
  release:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  fetchversion:
    name: set release version
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.set-app-version.outputs.VERSION }}
    steps:
      - name: "emit app version"
        id: set-app-version
        run: echo "VERSION=${GITHUB_REF}" >> $GITHUB_OUTPUT
  build_and_upload:
    name: Build and Upload
    runs-on: ubuntu-latest
    needs:
      - fetchversion
    env:
      CHASSY_TOKEN: ${{ secrets.CHASSY_TOKEN }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: Build
        run: cargo build --release

      - name: Upload package to Chassy Index
        uses: chassyflow/actions-package-upload@v2.0.0
        with:
          name: "web-pr-build"
          architecture: "AMD64"
          os: "ubuntu"
          os_version: "20.04"
          version: ${{ needs.fetchversion.outputs.app-version }}
          type: "FILE"
          path: "**/release/web"
          classification: "EXECUTABLE"
