name: Upload Cargo workspace Package

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_upload:
    name: Build and Upload
    runs-on: ubuntu-latest
    env:
      CHASSY_TOKEN: ${{ secrets.CHASSY_TOKEN_DEV }}
      BACKEND_ENV: DEV

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: Build
        run: cargo build --release

      - name: Upload package to Chassy Index
        uses: chassyflow/actions-package-upload@v2.0.0
        with:
          name: "web-pr-build"
          architecture: "AMD64"
          os: "ubuntu"
          os_version: "20.04"
          version: "0.0.1"
          type: "FILE"
          path: "**/release/web"
          classification: "EXECUTABLE"

  test_archive_features:
    name: Test Archive Features
    runs-on: ubuntu-latest
    env:
      CHASSY_TOKEN: ${{ secrets.CHASSY_TOKEN_DEV }}
      BACKEND_ENV: DEV

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: Upload archive bundle package to Chassy Index
        uses: chassyflow/actions-package-upload@v2.0.0
        with:
          name: "web source files"
          architecture: "AMD64"
          os: "ubuntu"
          os_version: "20.04"
          type: "ARCHIVE"
          path: "**/src/**/*.rs"
          classification: "BUNDLE"
