name: Upload Cargo workspace Package

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_upload:
    name: Build and Upload
    runs-on: ubuntu-latest
    env:
      CHASSY_TOKEN: ${{ secrets.CHASSY_ACCESS_TOKEN }}
      BACKEND_ENV: DEV

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: Build
        run: cargo build --release

      - name: Upload package to Chassy Index
        uses: chassyflow/actions-package-upload@master
        with:
          name: "web"
          architecture: "AMD64"
          os: "ubuntu"
          version: "20.04"
          type: "FILE"
          path: "**/release/web"
          classification: "EXECUTABLE"

  test_archive_features:
    name: Test Archive Features
    runs-on: ubuntu-latest
    env:
      CHASSY_TOKEN: ${{ secrets.CHASSY_ACCESS_TOKEN }}
      BACKEND_ENV: DEV

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: Upload archive bundle package to Chassy Index
        uses: chassyflow/actions-package-upload@master
        with:
          name: "web source files"
          architecture: "AMD64"
          os: "ubuntu"
          version: "20.04"
          type: "ARCHIVE"
          path: "**/src/**/*.rs"
          classification: "BUNDLE"

      - name: Upload pre-bundled archive package to Chassy Index
        uses: chassyflow/actions-package-upload@master
        with:
          name: "web source files"
          architecture: "AMD64"
          os: "ubuntu"
          version: "20.04"
          type: "ARCHIVE"
          path: "**/workspace_rs_src.zip"
          classification: "BUNDLE"
