[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
jmath = { path = "../jmath" }
anyhow = "1.0.93"
axum = "0.7.9"
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
